# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

# CocoaPodsの警告を抑制
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

workspace 'MyRDPApp.xcworkspace'
project 'MyRDPApp.xcodeproj'

target 'MyRDPApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # AWS SDK for iOS
  pod 'AWSCore'
  pod 'AWSEC2'
  pod 'AWSCognito'
  
  # Network monitoring
  pod 'Reachability'
  
  # Optional: For better logging
  pod 'CocoaLumberjack/Swift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
