name: MyRDPApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.3"
  generateEmptyDirectories: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  projectPath: ../MyRDPApp.xcodeproj

targets:
  MyRDPApp:
    type: application
    platform: iOS
    sources: 
      - path: MyRDPApp/
        excludes:
          - "build/**"
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: MyRDPApp/MyRDPApp-Bridging-Header.h
        SWIFT_VERSION: "5.0"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
        # ライブラリ検索パス（統一）
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
          - $(BUILT_PRODUCTS_DIR)/Libraries
        # リンクフラグ
        OTHER_LDFLAGS:
          - -lfreerdp3
          - -lwinpr3
          - -lssl
          - -lcrypto
          - -lz
      configs:
        Debug:
          ENABLE_TESTABILITY: "YES"
          # デバッグ用ヘッダーパス
          HEADER_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp/include
            - $(PROJECT_DIR)/Libraries/openssl/include
          HEADER_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp-simulator/include
            - $(PROJECT_DIR)/Libraries/openssl-simulator/include
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
          # リリース用ヘッダーパス
          HEADER_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp/include
            - $(PROJECT_DIR)/Libraries/openssl/include
          HEADER_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp-simulator/include
            - $(PROJECT_DIR)/Libraries/openssl-simulator/include
    dependencies:
      - sdk: libc++.tbd
      - sdk: libz.tbd
    info:
      path: MyRDPApp/Info.plist
      properties:
        CFBundleDisplayName: MyRDPApp
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    
    preBuildScripts:
      - name: "Copy FreeRDP Libraries"
        script: |
          # ライブラリコピー先ディレクトリの作成
          mkdir -p "$BUILT_PRODUCTS_DIR/Libraries"
          
          # シミュレータと実機でライブラリを切り替え
          if [[ "$PLATFORM_NAME" == "iphonesimulator" ]]; then
            echo "Copying simulator libraries..."
            cp -f "$PROJECT_DIR/Libraries/freerdp-simulator/lib/"*.a "$BUILT_PRODUCTS_DIR/Libraries/"
            cp -f "$PROJECT_DIR/Libraries/openssl-simulator/lib/"*.a "$BUILT_PRODUCTS_DIR/Libraries/"
          else
            echo "Copying device libraries..."
            cp -f "$PROJECT_DIR/Libraries/freerdp/lib/"*.a "$BUILT_PRODUCTS_DIR/Libraries/"
            cp -f "$PROJECT_DIR/Libraries/openssl/lib/"*.a "$BUILT_PRODUCTS_DIR/Libraries/"
          fi
          
          # コピーされたファイルの確認
          ls -la "$BUILT_PRODUCTS_DIR/Libraries/"
        outputFiles:
          - "$(BUILT_PRODUCTS_DIR)/Libraries/libfreerdp3.a"
          - "$(BUILT_PRODUCTS_DIR)/Libraries/libwinpr3.a"
          - "$(BUILT_PRODUCTS_DIR)/Libraries/libssl.a"
          - "$(BUILT_PRODUCTS_DIR)/Libraries/libcrypto.a"

schemes:
  MyRDPApp:
    build:
      targets:
        MyRDPApp: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release