name: MyRDPApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"  # iOS 15.0に更新
  xcodeVersion: "16.3"
  generateEmptyDirectories: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  projectPath: ../MyRDPApp.xcodeproj

targets:
  MyRDPApp:
    type: application
    platform: iOS
    sources: 
      - path: MyRDPApp/
        excludes:
          - "build/**"
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: MyRDPApp/MyRDPApp-Bridging-Header.h
        SWIFT_VERSION: "5.0"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
      configs:
        debug:
          ENABLE_TESTABILITY: "YES"
        release:
          SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    dependencies:
      - sdk: libc++.tbd
      - sdk: libz.tbd
    info:
      path: MyRDPApp/Info.plist
      properties:
        CFBundleDisplayName: MyRDPApp
        UILaunchStoryboardName: MyRDPApp/LaunchScreen
        UIMainStoryboardFile: Main
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    
    preBuildScripts:
      - name: "Copy FreeRDP Libraries"
        script: |
          # シミュレータと実機でライブラリを切り替え
          mkdir -p "$BUILT_PRODUCTS_DIR/Libraries"
          if [[ "$PLATFORM_NAME" == "iphonesimulator" ]]; then
            cp -f "$PROJECT_DIR/Libraries/freerdp-simulator/lib/"*.a "$BUILT_PRODUCTS_DIR/Libraries/"
            cp -f "$PROJECT_DIR/Libraries/openssl-simulator/lib/"*.a "$BUILT_PRODUCTS_DIR/Libraries/"
          else
            cp -f "$PROJECT_DIR/Libraries/freerdp/lib/"*.a "$BUILT_PRODUCTS_DIR/Libraries/"
            cp -f "$PROJECT_DIR/Libraries/openssl/lib/"*.a "$BUILT_PRODUCTS_DIR/Libraries/"
          fi
        outputFiles:
          - "$(BUILT_PRODUCTS_DIR)/Libraries/libfreerdp3.a"
          - "$(BUILT_PRODUCTS_DIR)/Libraries/libwinpr3.a"
          - "$(BUILT_PRODUCTS_DIR)/Libraries/libssl.a"
          - "$(BUILT_PRODUCTS_DIR)/Libraries/libcrypto.a"
    
    buildSettings:
      LIBRARY_SEARCH_PATHS:
        - $(inherited)
        - $(PROJECT_DIR)/Libraries/Device/lib
        - $(PROJECT_DIR)/Libraries/Simulator/lib
      HEADER_SEARCH_PATHS:
        - $(inherited)
        - $(PROJECT_DIR)/Libraries/Device/include
        - $(PROJECT_DIR)/Libraries/Simulator/include
      OTHER_LDFLAGS:
        - -lfreerdp3
        - -lwinpr3
        - -lssl
        - -lcrypto
        - -lz

schemes:
  MyRDPApp:
    build:
      targets:
        MyRDPApp: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 