name: MyRDPApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.3"
  generateEmptyDirectories: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  projectPath: ../MyRDPApp.xcodeproj

targets:
  MyRDPApp:
    type: application
    platform: iOS
    sources: 
      - path: MyRDPApp/
        excludes:
          - "build/**"
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: MyRDPApp/MyRDPApp-Bridging-Header.h
        SWIFT_VERSION: "5.0"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
        # リンクフラグ
        OTHER_LDFLAGS:
          - -lfreerdp3
          - -lwinpr3
          - -lssl
          - -lcrypto
          - -lz
      configs:
        Debug:
          ENABLE_TESTABILITY: "YES"
          # デバッグ用ライブラリ・ヘッダーパス
          LIBRARY_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp/lib
            - $(PROJECT_DIR)/Libraries/openssl/lib
          LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp-simulator/lib
            - $(PROJECT_DIR)/Libraries/openssl-simulator/lib
          HEADER_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp/include
            - $(PROJECT_DIR)/Libraries/openssl/include
          HEADER_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp-simulator/include
            - $(PROJECT_DIR)/Libraries/openssl-simulator/include
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
          # リリース用ライブラリ・ヘッダーパス
          LIBRARY_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp/lib
            - $(PROJECT_DIR)/Libraries/openssl/lib
          LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp-simulator/lib
            - $(PROJECT_DIR)/Libraries/openssl-simulator/lib
          HEADER_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp/include
            - $(PROJECT_DIR)/Libraries/openssl/include
          HEADER_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/Libraries/freerdp-simulator/include
            - $(PROJECT_DIR)/Libraries/openssl-simulator/include
    dependencies:
      - sdk: libc++.tbd
      - sdk: libz.tbd
    info:
      path: MyRDPApp/Info.plist
      properties:
        CFBundleDisplayName: MyRDPApp
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

schemes:
  MyRDPApp:
    build:
      targets:
        MyRDPApp: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release